 ---------------------------------------------------------------
 Vortex Lattice Output -- Total Forces

 Configuration: Aircraft                                                    
     # Surfaces =   4
     # Strips   =  80
     # Vortices =1600

  Sref = 0.53774       Cref = 0.29937       Bref =  1.7962    
  Xref = 0.79310E-01   Yref =  0.0000       Zref =  0.0000    

 Standard axis orientation,  X fwd, Z down         

 Run case:  -unnamed-                              

  Alpha =   1.73532     pb/2V =  -0.00000     p'b/2V =  -0.00000
  Beta  =   0.00000     qc/2V =   0.00000
  Mach  =     0.000     rb/2V =  -0.00000     r'b/2V =  -0.00000

  CXtot =   0.00397     Cltot =  -0.00000     Cl'tot =  -0.00000
  CYtot =   0.00000     Cmtot =  -0.00000
  CZtot =  -0.23109     Cntot =  -0.00000     Cn'tot =  -0.00000

  CLtot =   0.23111
  CDtot =   0.00303
  CDvis =   0.00000     CDind = 0.0030257
  CLff  =   0.23117     CDff  = 0.0030225    | Trefftz
  CYff  =  -0.00000         e =    0.9380    | Plane  

   elevator        =   0.00022

 ---------------------------------------------------------------

 Stability-axis derivatives...

                             alpha                beta
                  ----------------    ----------------
 z' force CL |    CLa =   4.721474    CLb =  -0.000000
 y  force CY |    CYa =  -0.000000    CYb =  -0.244721
 x' mom.  Cl'|    Cla =   0.000000    Clb =  -0.069139
 y  mom.  Cm |    Cma =  -1.020823    Cmb =  -0.000000
 z' mom.  Cn'|    Cna =   0.000000    Cnb =   0.098421

                     roll rate  p'      pitch rate  q'        yaw rate  r'
                  ----------------    ----------------    ----------------
 z' force CL |    CLp =  -0.000000    CLq =   8.246707    CLr =   0.000000
 y  force CY |    CYp =   0.030384    CYq =   0.000000    CYr =   0.217026
 x' mom.  Cl'|    Clp =  -0.444743    Clq =  -0.000000    Clr =   0.100609
 y  mom.  Cm |    Cmp =   0.000000    Cmq =  -9.576535    Cmr =   0.000000
 z' mom.  Cn'|    Cnp =  -0.007376    Cnq =   0.000000    Cnr =  -0.089084

                  elevator     d1 
                  ----------------
 z' force CL |   CLd1 =   0.017663
 y  force CY |   CYd1 =   0.000000
 x' mom.  Cl'|   Cld1 =  -0.000000
 y  mom.  Cm |   Cmd1 =  -0.038555
 z' mom.  Cn'|   Cnd1 =  -0.000000
 Trefftz drag| CDffd1 =   0.000194
 span eff.   |    ed1 =   0.083462



 Neutral point  Xnp =   0.144036

 Clb Cnr / Clr Cnb  =   0.622018    (  > 1 if spirally stable )
